//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace azilZaPse.Models.Repository_Ef_Baza
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AzilZaPseEntities1 : DbContext
    {
        public AzilZaPseEntities1()
            : base("name=AzilZaPseEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dokumentacija> Dokumentacijas { get; set; }
        public virtual DbSet<KartonPsa> KartonPsas { get; set; }
        public virtual DbSet<Kuce> Kuces { get; set; }
        public virtual DbSet<Proizvod> Proizvods { get; set; }
        public virtual DbSet<Proizvodjac> Proizvodjacs { get; set; }
        public virtual DbSet<Proizvodnja> Proizvodnjas { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Vlasnik> Vlasniks { get; set; }
        public virtual DbSet<Korisnik> Korisniks { get; set; }
    }
}
