//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace azilZaPse.Models.Repository_Ef_Baza
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dokumentacija
    {
        public int idDokumentacije { get; set; }
        public string tekstDokumentacije { get; set; }
        public string datumIzdavanja { get; set; }
        public int idCipa { get; set; }
        public string idVlasnika { get; set; }
    
        public virtual Kuce Kuce { get; set; }
        public virtual Vlasnik Vlasnik { get; set; }
    }
}
