//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace azilZaPse.Models.Repository_Ef_Baza
{
    using System;
    using System.Collections.Generic;
    
    public partial class KartonPsa
    {
        public int idCipa { get; set; }
        public Nullable<bool> daLiJeVakcinisan { get; set; }
        public string alergije { get; set; }
        public Nullable<bool> ociscenOdParazita { get; set; }
    
        public virtual Kuce Kuce { get; set; }
    }
}
