//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace azilZaPse.Models.Repository_Ef_Baza
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kuce
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kuce()
        {
            this.Dokumentacijas = new HashSet<Dokumentacija>();
        }
    
        public int idCipa { get; set; }
        public string rasa { get; set; }
        public string pol { get; set; }
        public int starost { get; set; }
        public string ime { get; set; }
        public string idVlasnika { get; set; }
        public Nullable<bool> uAzilu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dokumentacija> Dokumentacijas { get; set; }
        public virtual KartonPsa KartonPsa { get; set; }
        public virtual Vlasnik Vlasnik { get; set; }
    }
}
