//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace azilZaPse.Models.Repository_Ef_Baza
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proizvodjac
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proizvodjac()
        {
            this.Proizvodnjas = new HashSet<Proizvodnja>();
        }
    
        public int idProizvodjaca { get; set; }
        public string nazivProizvodjaca { get; set; }
        public string grad { get; set; }
        public string ulica { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proizvodnja> Proizvodnjas { get; set; }
    }
}
