//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace azilZaPse.Models.Repository_Ef_Baza
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proizvodnja
    {
        public int idProizvoda { get; set; }
        public int idProizvodjaca { get; set; }
        public Nullable<int> dostupneKolicine { get; set; }
    
        public virtual Proizvod Proizvod { get; set; }
        public virtual Proizvodjac Proizvodjac { get; set; }
    }
}
